export const MOVIE_LIST_ACTION_TYPES={
    MOVIE_LIST_REQUEST:"movie/MOVIE_LIST_REQUEST",
    MOVIE_LIST_SUCCESS:"movie/MOVIE_LIST_SUCCESS",
    MOVIE_LIST_FAIL:"movie/MOVIE_LIST_FAIL",
}

export const MOVIE_DETAILS_ACTION_TYPES={
    MOVIE_DETAILS_REQUEST:"movie/MOVIE_DETAILS_REQUEST",
    MOVIE_DETAILS_SUCCESS:"movie/MOVIE_DETAILS_SUCCESS",
    MOVIE_DETAILS_FAIL:"movie/MOVIE_DETAILS_FAIL",
}
