export const USER_LOGIN_ACTION_TYPES={
    USER_LOGIN_REQUEST:"user/USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS:"user/USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL:"user/USER_LOGIN_FAIL",
    USER_LOGOUT:"user/USER_LOGOUT",
}
